import Head from 'next/head'
import HomeProducts from '@/components/HomeProducts'
import { Carousel } from 'react-bootstrap'



export default function Home() {
  let allProducts = [
    {
      title: 'T-Shirt',
      img: ['https://m.media-amazon.com/images/I/61Vmw6ZbCBL._UX679_.jpg', "https://m.media-amazon.com/images/I/61zdaycq0sL._UX679_.jpg", "https://m.media-amazon.com/images/I/71ivjRqbCwL._AC_UL320_.jpg", "https://m.media-amazon.com/images/I/81mMnJRxZvL._UY741_.jpg"],
      link: '/tshirt',
      des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, soluta!'
    },
    {
      title: 'Hoodies',
      img: ['https://m.media-amazon.com/images/I/61YWB-llUbL._AC_UL400_.jpg', 'https://m.media-amazon.com/images/I/41KKqbZ3QKL._UX569_.jpg', 'https://m.media-amazon.com/images/I/61vL2zeS83L._UY741_.jpg', 'https://m.media-amazon.com/images/I/81GlGm+rrRS._AC_UL320_.jpg'],
      link: '/hoodies',
      des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, soluta!'
    },
    {
      title: 'Mugs',
      img: ['https://m.media-amazon.com/images/I/81ekFNzJSLL._AC_UL400_.jpg', "https://m.media-amazon.com/images/I/71KAQJDAtEL._AC_UL320_.jpg", "https://m.media-amazon.com/images/I/71OygAncxpL._AC_UL320_.jpg", "https://m.media-amazon.com/images/I/31wrTvQLdxL._AC_UL320_.jpg",],
      link: '/mugs',
      des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, soluta!'
    },
    {
      title: 'shoes',
      img: ['https://m.media-amazon.com/images/I/61utX8kBDlL._AC_UL400_.jpg', 'https://m.media-amazon.com/images/I/51AtSO1qaCL._UY625_.jpg', 'https://m.media-amazon.com/images/I/71RYdJqpyTL._UY695_.jpg', 'https://m.media-amazon.com/images/I/717k2GxaGZL._UY695_.jpg'],
      link: '/shoes',
      des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, soluta!'
    },
    {
      title: 'Bags',
      img: ['https://m.media-amazon.com/images/I/91kIW19BBkL._AC_UL400_.jpg', 'https://m.media-amazon.com/images/I/81AWrc5E0cL._SX679_.jpg', 'https://m.media-amazon.com/images/I/61mz+MAOvOL._UY695_.jpg', 'https://m.media-amazon.com/images/I/71eHC9b52VL._UY695_.jpg'],
      link: '/bags',
      des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, soluta!'
    },
    {
      title: 'Stationary',
      img: ['https://m.media-amazon.com/images/I/711xStHar2L._SL1500_.jpg', 'https://m.media-amazon.com/images/I/71cY0PcxS7L._AC_UL320_.jpg', "https://m.media-amazon.com/images/I/3127jkyejvL._AC_UL320_.jpg", "https://m.media-amazon.com/images/I/71CUaxW+IdL._AC_UL320_.jpg"],
      link: '/stationary',
      des: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, soluta!'
    }
  ]
  return (
    <>
      <Head>
        <title>E-Commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel className='mt-5 pt-5'>
        <Carousel.Item >
          <img width={1300} height={800}
            className="d-block m-auto  "
            src="/photo-1483985988355-763728e1935b.avif"
            alt="First slide"
          />
          <Carousel.Caption>
            <h1>CUSTOMIZED DESIGNE</h1>
            <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
          </Carousel.Caption>
        </Carousel.Item>
        <Carousel.Item >
          <img width={1300} height={800}
            className="d-block m-auto "
            src="/home.jpg"
            alt="Second slide"
          />
         
        </Carousel.Item>
        <Carousel.Item>
          <img width={1300} height={800}
            className="d-block  m-auto "
            src="/home2.jpg"
            alt="Third slide"
          />
           <Carousel.Caption>
            <h1>EXCLUSIVE DISCOUNT</h1>
            <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
          </Carousel.Caption>
        </Carousel.Item>
      </Carousel>

      <div className='container-md mt-5 pt-5'>
        <div className="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 py-5">
          {
            allProducts.map((x, i) => {
              return <HomeProducts img={x.img} title={x.title} link={x.link} des={x.des} key={i} />
            })
          }
        </div>
      </div>
    </>
  )
}
